# Generated by Django 3.2 on 2022-09-03 09:03

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikeToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'bot_liketouser',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Image or Video file', storage=django.core.files.storage.FileSystemStorage(location='/.images'), upload_to='')),
                ('file_type', models.CharField(choices=[('image/jpg', 'JPG'), ('image/png', 'PNG'), ('video/mp4', 'MP4'), ('gif/gif', 'GIF')], default='image/jpg', help_text='The file type', max_length=20)),
            ],
            options={
                'db_table': 'bot_media',
            },
        ),
        migrations.CreateModel(
            name='RtToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'bot_rttouser',
            },
        ),
        migrations.CreateModel(
            name='Seiyuu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Seiyuu Name', max_length=20)),
            ],
            options={
                'db_table': 'bot_seiyuu',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.IntegerField(help_text='The UID of user object in twitter API', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Display name', max_length=255)),
                ('screen_name', models.CharField(blank=True, help_text='ID name (with @ sign)', max_length=255)),
                ('location', models.CharField(blank=True, help_text='The location in their profile', max_length=255)),
                ('protected', models.BooleanField(blank=True, help_text='If the account is private')),
                ('verified', models.BooleanField(blank=True, help_text='If the account has the blue check mark')),
                ('followers', models.IntegerField(blank=True, help_text='The # of followers (fans)', null=True)),
                ('followings', models.IntegerField(blank=True, help_text='The # of followings', null=True)),
            ],
            options={
                'db_table': 'bot_useraccount',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.IntegerField(help_text='Tweet ID', primary_key=True, serialize=False)),
                ('post_time', models.DateTimeField(blank=True, help_text='Tweet time', null=True)),
                ('data_time', models.DateTimeField(blank=True, help_text='Data collected time', null=True)),
                ('like', models.SmallIntegerField(blank=True, help_text='Likes', null=True)),
                ('rt', models.SmallIntegerField(blank=True, help_text='Retweets', null=True)),
                ('rt_spread', models.SmallIntegerField(blank=True, help_text='Sum of followers of all RTing users', null=True)),
                ('follower', models.SmallIntegerField(blank=True, help_text='Followers', null=True)),
                ('like_user', models.ManyToManyField(blank=True, help_text='The user list that likes this tweet', related_name='likes', through='twitter_bot.LikeToUser', to='twitter_bot.UserAccount')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twitter_bot.media')),
                ('rt_user', models.ManyToManyField(blank=True, help_text='The user list that RT this tweet', related_name='rts', through='twitter_bot.RtToUser', to='twitter_bot.UserAccount')),
            ],
            options={
                'db_table': 'bot_tweet',
            },
        ),
        migrations.AddField(
            model_name='rttouser',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_bot.tweet'),
        ),
        migrations.AddField(
            model_name='rttouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_bot.useraccount'),
        ),
        migrations.AddField(
            model_name='media',
            name='seiyuu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twitter_bot.seiyuu'),
        ),
        migrations.AddField(
            model_name='liketouser',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_bot.tweet'),
        ),
        migrations.AddField(
            model_name='liketouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_bot.useraccount'),
        ),
    ]
