# Generated by Django 3.2 on 2022-09-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0003_tweet_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='weight',
        ),
        migrations.AddField(
            model_name='media',
            name='weight',
            field=models.FloatField(default=1.0, help_text='Weight for random choice'),
        ),
    ]
