# Generated by Django 3.2 on 2023-02-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0004_auto_20220911_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='analyzed',
            field=models.BooleanField(default=False, help_text='Whether the tweet has been analyzed'),
        ),
        migrations.CreateModel(
            name='WeeklyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the week')),
                ('end_date', models.DateField(help_text='End date of the week')),
                ('avg_likes', models.FloatField(help_text='Average number of likes of all tweets this week')),
                ('avg_retweets', models.FloatField(help_text='Average number of retweets of all tweets this week')),
                ('delta_followers', models.IntegerField(help_text='Delta of followers compared to last week')),
                ('max_likes', models.ForeignKey(help_text='Tweet instance with the highest number of likes this week', on_delete=django.db.models.deletion.CASCADE, related_name='max_likes_stats', to='twitter_bot.tweet')),
                ('max_likes_all', models.ForeignKey(help_text='Tweet instance with the highest number of likes of all time', on_delete=django.db.models.deletion.CASCADE, related_name='max_likes_stats_all', to='twitter_bot.tweet')),
                ('max_rt_all', models.ForeignKey(help_text='Tweet instance with the highest number of retweets of all time', on_delete=django.db.models.deletion.CASCADE, related_name='max_rt_stats_all', to='twitter_bot.tweet')),
                ('max_rts', models.ForeignKey(help_text='Tweet instance with the highest number of retweets this week', on_delete=django.db.models.deletion.CASCADE, related_name='max_rt_stats', to='twitter_bot.tweet')),
                ('most_active_user', models.ForeignKey(help_text='The most active user this week, who appears most frequently in the field rt_user of all tweets', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_stats', to='twitter_bot.useraccount')),
            ],
            options={
                'db_table': 'weekly_stats',
            },
        ),
    ]
