# Generated by Django 3.2 on 2023-02-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0008_weeklystats_seiyuu'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklystats',
            name='likes',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of liks this week', null=True),
        ),
        migrations.AddField(
            model_name='weeklystats',
            name='likes_all',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of liks of all time', null=True),
        ),
        migrations.AddField(
            model_name='weeklystats',
            name='posts',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of posts this week', null=True),
        ),
        migrations.AddField(
            model_name='weeklystats',
            name='posts_all',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of posts of all time', null=True),
        ),
        migrations.AddField(
            model_name='weeklystats',
            name='rts',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of rts this week', null=True),
        ),
        migrations.AddField(
            model_name='weeklystats',
            name='rts_all',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of rts of all time', null=True),
        ),
    ]
