# Generated by Django 3.2 on 2023-02-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0009_auto_20230219_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='seiyuu',
            name='id_name',
            field=models.CharField(blank=True, help_text='Seiyuu short name', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seiyuu',
            name='screen_name',
            field=models.CharField(blank=True, help_text='Bot account screen name', max_length=20, null=True),
        ),
    ]
