# Generated by Django 3.2 on 2023-06-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0010_auto_20230221_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='list_count',
            field=models.SmallIntegerField(blank=True, help_text='number of lists include this account', null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='quote',
            field=models.SmallIntegerField(blank=True, help_text='number of quotes', null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='reply',
            field=models.SmallIntegerField(blank=True, help_text='number of replies', null=True),
        ),
    ]
