# Generated by Django 3.2 on 2023-07-29 14:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0011_auto_20230609_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('data_time', models.DateTimeField(auto_now_add=True, help_text='Data collected time')),
                ('followers', models.IntegerField(blank=True, help_text='Current followers', null=True)),
                ('seiyuu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='twitter_bot.seiyuu')),
            ],
            options={
                'db_table': 'bot_followers',
            },
        ),
    ]
