# Generated by Django 3.2 on 2023-11-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0013_alter_followers_data_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='seiyuu',
            name='activated',
            field=models.BooleanField(default=True, help_text='If the bot is activated'),
        ),
        migrations.AddField(
            model_name='seiyuu',
            name='interval',
            field=models.IntegerField(default=1, help_text='Interval between tweets in hours'),
        ),
        migrations.AlterField(
            model_name='seiyuu',
            name='id_name',
            field=models.CharField(blank=True, help_text='Seiyuu short name, example: kaorin', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seiyuu',
            name='name',
            field=models.CharField(help_text='Seiyuu Name, exmaple: 前田佳織里', max_length=20),
        ),
        migrations.AlterField(
            model_name='seiyuu',
            name='screen_name',
            field=models.CharField(blank=True, help_text='Bot account screen name, example: kaorin__bot', max_length=20, null=True),
        ),
    ]
