# Generated by Django 3.2 on 2023-11-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0014_auto_20231102_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='seiyuu',
            name='image_folder',
            field=models.CharField(blank=True, help_text='The folder name of the images', max_length=20, null=True),
        ),
    ]
