# Generated by Django 3.2 on 2023-12-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0015_seiyuu_image_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='seiyuu',
            name='hidden',
            field=models.BooleanField(default=False, help_text='If the seiyuu should be hidden from website'),
        ),
    ]
