# Generated by Django 3.2 on 2022-11-21 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20221121_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['time', 'create_time']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['order__expect_arrival', 'create_time', 'name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['expect_arrival', 'create_time']},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['owner__name', 'name']},
        ),
    ]
