# Generated by Django 3.2 on 2022-11-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, help_text='訂單編號', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, help_text='購買來源(amazon, gamers, etc.)', max_length=50, null=True),
        ),
    ]
