# Generated by Django 3.2 on 2022-12-01 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_auto_20221125_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_status',
        ),
        migrations.AddField(
            model_name='item',
            name='delivery_cost',
            field=models.PositiveIntegerField(blank=True, help_text='運費', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, help_text='狀態', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, help_text='狀態，統計管理用', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='delivery',
            field=models.ForeignKey(blank=True, help_text='交貨安排', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='logistics.delivery'),
        ),
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.ForeignKey(blank=True, help_text='隸屬訂單', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='logistics.order'),
        ),
    ]
