# Generated by Django 3.2 on 2023-10-07 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='App name', max_length=50, null=True)),
                ('router', models.CharField(blank=True, help_text='App URL router', max_length=50, null=True)),
                ('auth_required', models.BooleanField(default=False, help_text='Whether authentication is required')),
            ],
            options={
                'db_table': 'auth_app',
            },
        ),
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, help_text='User nickname', max_length=20, null=True)),
                ('app', models.ForeignKey(help_text='App which the user belongs to', on_delete=django.db.models.deletion.CASCADE, to='local_auth.app')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_userextend',
            },
        ),
    ]
